# Generated by Django 4.0.4 on 2022-05-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdown',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
