# Generated by Django 4.0.4 on 2022-05-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_name_dropdown_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropdown',
            old_name='title',
            new_name='name',
        ),
    ]
