# Generated by Django 4.0.4 on 2022-05-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_title_dropdown_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropdown',
            old_name='name',
            new_name='title',
        ),
    ]
