# Generated by Django 4.0.4 on 2022-05-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_name_dropdown_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdown',
            name='title',
            field=models.CharField(default='title_d', max_length=225),
        ),
    ]
