# Generated by Django 4.0.4 on 2022-05-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dropdown_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='uuid',
            new_name='movie_id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Kids', 'Kids')], default='All', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('single', 'single'), ('seasonal', 'seasonal')], default='single', max_length=10),
        ),
    ]
