# Generated by Django 4.0.4 on 2022-05-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_uuid_movie_movie_id_alter_movie_age_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(default=-12, unique=True),
        ),
    ]
